export const LOAD_QUESTIONS = "LOAD_QUESTIONS";

export const STORE_QUESTIONS = "STORE_QUESTIONS";

export const GET_QUESTIONS = "GET_QUESTIONS";
export const ADD_QUESTION = "ADD_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";

export const EDIT_MODE = "EDIT_MODE";
export const ADD_MODE = "ADD_MODE";
