export const LOAD_QUESTIONS = "LOAD_QUESTIONS";
export const STORE_QUESTIONS = "STORE_QUESTIONS";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const ADD_QUESTION = "ADD_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";

export const LOAD_RESPONSES = "LOAD_RESPONSES";
export const STORE_RESPONSES = "STORE_RESPONSES";
export const GET_RESPONSES = "GET_RESPONSES";
export const ADD_RESPONSE = "ADD_RESPONSE";
export const DELETE_RESPONSE = "DELETE_RESPONSE";
export const UPDATE_RESPONSE = "UPDATE_RESPONSE";

export const LOAD_SKILLS = "LOAD_SKILLS";
export const STORE_SKILLS = "STORE_SKILLS";
export const GET_SKILLS = "GET_SKILLS";
export const ADD_SKILL = "ADD_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";
export const UPDATE_SKILL = "UPDATE_SKILL";

export const QUESTION_EDIT_MODE = "QUESTION_EDIT_MODE ";
export const QUESTION_ADD_MODE = "QUESTION_ADD_MODE ";

export const RESPONSE_EDIT_MODE = "RESPONSE_EDIT_MODE";
export const RESPONSE_ADD_MODE = "RESPONSE_ADD_MODE";

export const SKILL_EDIT_MODE = "SKILL_EDIT_MODE";
export const SKILL_ADD_MODE = "SKILL_ADD_MODE";
