export const LOAD_INTENTS = "LOAD_INTENTS";
export const STORE_INTENTS = "STORE_INTENTS";
export const GET_INTENTS = "GET_INTENTS";
export const ADD_INTENT = "ADD_INTENT";
export const DELETE_INTENT = "DELETE_INTENT";
export const UPDATE_INTENT = "UPDATE_INTENT";

export const LOAD_RESPONSES = "LOAD_RESPONSES";
export const STORE_RESPONSES = "STORE_RESPONSES";
export const GET_RESPONSES = "GET_RESPONSES";
export const ADD_RESPONSE = "ADD_RESPONSE";
export const DELETE_RESPONSE = "DELETE_RESPONSE";
export const UPDATE_RESPONSE = "UPDATE_RESPONSE";

export const LOAD_SKILLS = "LOAD_SKILLS";
export const STORE_SKILLS = "STORE_SKILLS";
export const GET_SKILLS = "GET_SKILLS";
export const ADD_SKILL = "ADD_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";
export const UPDATE_SKILL = "UPDATE_SKILL";

export const LOAD_STORIES = "LOAD_STORIES";
export const STORE_STORIES = "STORE_STORIES";
export const GET_STORIES = "GET_STORIES";
export const ADD_STORY = "ADD_STORY";
export const DELETE_STORY = "DELETE_STORY";
export const UPDATE_STORY = "UPDATE_STORY";

export const INTENT_EDIT_MODE = "INTENT_EDIT_MODE ";
export const INTENT_ADD_MODE = "INTENT_ADD_MODE ";

export const RESPONSE_EDIT_MODE = "RESPONSE_EDIT_MODE";
export const RESPONSE_ADD_MODE = "RESPONSE_ADD_MODE";

export const SKILL_EDIT_MODE = "SKILL_EDIT_MODE";
export const SKILL_ADD_MODE = "SKILL_ADD_MODE";

export const STORY_EDIT_MODE = "STORY_EDIT_MODE";
export const STORY_ADD_MODE = "STORY_ADD_MODE";
